### ISSUE TITLE
Download key needs to be "serialized" in some way

### ISSUE THREAD

**Issue by scaramonche** [Proteobench/ProteoBench#90]
When I try to "parse and bench" two files in a row, I get the error below
`streamlit.errors.DuplicateWidgetID: There are multiple identical `st.download_button` widgets with the same generated key.`

**Comment by RobbinBouwmeester** [comment]
@scaramonche what elements exactly?

**Comment by scaramonche** [comment]
I have to test again, but basically it happened when I uploaded several files in a row. And it happened for several different input text boxes and buttons that are in the code and get reloaded.

**Comment by RobbinBouwmeester** [comment]
All input fields and buttons need to be unique, the submit button is fixed, others should be fixed

**Comment by mlocardpaulet** [comment]
I still have the error message when I load two runs in a row (Proline and then MQ) without indicating any parameters:
![image](https://github.com/Proteobench/ProteoBench/assets/8386272/f70851cd-2e88-4ee9-9086-bfc4dcea186d)
I suspect that it is related to this issue.

**Comment by scaramonche** [comment]
Yes, exactly, that is this issue. Thanks for confirming that it is not just an issue for me since I was not entirely sure.

**Comment by RobbinBouwmeester** [comment]
Fixed in #175
